-- ============================================================
-- FRESHLINK PRO — SUPABASE SCHEMA v1.0
-- Generated by BLACKBOX AI (Jawad / OURAI / ASHEL Team)
-- Run in Supabase SQL Editor → Execute
-- ============================================================

-- ── EXTENSIONS ────────────────────────────────────────────────
create extension if not exists "pgcrypto";

-- ── ENUMS ─────────────────────────────────────────────────────
do $$ begin
  create type user_role as enum (
    'super_admin','admin','resp_commercial','team_leader',
    'prevendeur','resp_logistique','magasinier','dispatcheur','livreur',
    'acheteur','ctrl_achat','ctrl_prep',
    'cash_man','financier','rh_manager','comptable',
    'client','fournisseur'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type access_type as enum ('mobile','backoffice','both');
exception when duplicate_object then null; end $$;

do $$ begin
  create type classification_rh as enum ('salarie','actionnaire','both');
exception when duplicate_object then null; end $$;

do $$ begin
  create type hr_doc_type as enum ('contrat','fiche_paie','attestation','conge','avertissement');
exception when duplicate_object then null; end $$;

do $$ begin
  create type order_status as enum (
    'brouillon','confirme','en_preparation','pret','en_livraison',
    'livre','retour_partiel','retour_total','annule'
  );
exception when duplicate_object then null; end $$;

-- ── TABLE: depots ──────────────────────────────────────────────
create table if not exists depots (
  id              uuid primary key default gen_random_uuid(),
  nom             text not null,
  ville           text,
  adresse         text,
  responsable_nom text,
  actif           boolean not null default true,
  created_at      timestamptz not null default now()
);

-- ── TABLE: users ──────────────────────────────────────────────
-- Maps 1:1 to Supabase Auth (auth.users). id = auth.users.id
create table if not exists users (
  id              uuid primary key references auth.users(id) on delete cascade,
  name            text not null,
  email           text not null unique,
  role            user_role not null default 'prevendeur',
  access_type     access_type,
  secteur         text,
  phone           text,
  telephone       text,           -- WhatsApp intl format ex: 212661234567
  actif           boolean not null default true,
  photo_url       text,
  depot_id        uuid references depots(id) on delete set null,

  -- HR Classification (OURAI)
  classification  classification_rh,
  matricule       text unique,    -- Auto-generated: FL-YYYYROLE-NNN
  date_embauche   date,
  salaire_base    numeric(10,2),

  -- Permissions
  can_view_achat          boolean not null default false,
  can_view_commercial     boolean not null default false,
  can_view_logistique     boolean not null default false,
  can_view_stock          boolean not null default false,
  can_view_cash           boolean not null default false,
  can_view_finance        boolean not null default false,
  can_view_recap          boolean not null default false,
  can_view_database       boolean not null default false,
  can_view_rh             boolean not null default false,
  can_view_external       boolean not null default false,
  can_create_commande_bo  boolean not null default false,

  -- Objectifs prévendeur
  objectif_clients            int default 0,
  objectif_tonnage            int default 0,
  objectif_journalier_ca      numeric(10,2) default 0,
  objectif_hebdomadaire_ca    numeric(10,2) default 0,
  objectif_mensuel_ca         numeric(10,2) default 0,
  objectif_journalier_clients int default 0,
  objectif_hebdomadaire_clients int default 0,
  objectif_mensuel_clients    int default 0,

  -- Security
  require_camera_auth boolean default false,
  password_mobile     text,
  password_bo         text,

  -- Portal linking
  fournisseur_id  uuid,
  client_id       uuid,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- Auto-update updated_at
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

drop trigger if exists users_updated_at on users;
create trigger users_updated_at
  before update on users
  for each row execute function set_updated_at();

-- Auto-generate matricule when classification = 'salarie' or 'both'
create or replace function generate_matricule()
returns trigger language plpgsql as $$
declare
  role_code text;
  year_code text;
  seq_num   int;
  new_mat   text;
begin
  if new.matricule is null and new.classification in ('salarie','both') then
    role_code := case new.role
      when 'prevendeur'      then 'PRV'
      when 'livreur'         then 'LIV'
      when 'magasinier'      then 'MAG'
      when 'acheteur'        then 'ACH'
      when 'resp_logistique' then 'LOG'
      when 'resp_commercial' then 'COM'
      when 'dispatcheur'     then 'DIS'
      when 'cash_man'        then 'CSH'
      when 'financier'       then 'FIN'
      when 'rh_manager'      then 'RHM'
      when 'comptable'       then 'CPT'
      when 'admin'           then 'ADM'
      when 'super_admin'     then 'SPA'
      else 'EMP'
    end;
    year_code := to_char(now(), 'YYYY');
    select coalesce(max(cast(right(matricule,3) as int)),0) + 1
      into seq_num
      from users
      where matricule like 'FL-' || year_code || role_code || '-%';
    new_mat := 'FL-' || year_code || role_code || '-' || lpad(seq_num::text, 3, '0');
    new.matricule := new_mat;
  end if;
  return new;
end $$;

drop trigger if exists users_matricule on users;
create trigger users_matricule
  before insert on users
  for each row execute function generate_matricule();

-- ── TABLE: products / catalogue ───────────────────────────────
create table if not exists products (
  id              uuid primary key default gen_random_uuid(),
  sku             text not null unique,
  name            text not null,
  name_ar         text,
  category        text,           -- fruits, legumes, herbes, surgeles...
  unit            text not null default 'kg',  -- kg, piece, caisse, palette
  price_achat     numeric(10,2),
  price_vente     numeric(10,2),
  prix_plancher   numeric(10,2),  -- prix min vente (Jawad)
  stock_actuel    numeric(10,3) default 0,
  stock_securite  numeric(10,3) default 0,
  actif           boolean not null default true,
  image_url       text,
  depot_id        uuid references depots(id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists products_updated_at on products;
create trigger products_updated_at
  before update on products
  for each row execute function set_updated_at();

-- ── TABLE: clients ────────────────────────────────────────────
create table if not exists clients (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  type_client     text,           -- marchand, restaurant, hotel, grossiste...
  adresse         text,
  ville           text,
  phone           text,
  email           text,
  responsable     text,           -- nom du propriétaire/gérant (Zizi target)
  secteur         text,
  prevendeur_id   uuid references users(id) on delete set null,
  modalite_paiement text default 'cash',
  credit_encours  numeric(10,2) default 0,
  credit_max      numeric(10,2) default 0,
  actif           boolean not null default true,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists clients_updated_at on clients;
create trigger clients_updated_at
  before update on clients
  for each row execute function set_updated_at();

-- ── TABLE: fournisseurs ───────────────────────────────────────
create table if not exists fournisseurs (
  id              uuid primary key default gen_random_uuid(),
  name            text not null,
  type_produits   text,           -- fruits, legumes, mixte
  adresse         text,
  ville           text,
  phone           text,
  email           text,
  responsable     text,
  modalite_paiement text default 'cash',
  credit_encours  numeric(10,2) default 0,
  credit_max      numeric(10,2) default 0,
  score_qualite   int default 5,  -- 1 à 10 (ASHEL)
  actif           boolean not null default true,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

-- ── TABLE: prix_historique_fournisseur ────────────────────────
-- Historique prix par SKU/fournisseur — used by ASHEL & Simohammed
create table if not exists prix_historique_fournisseur (
  id              uuid primary key default gen_random_uuid(),
  fournisseur_id  uuid not null references fournisseurs(id) on delete cascade,
  product_id      uuid not null references products(id) on delete cascade,
  prix_achat      numeric(10,2) not null,
  quantite_kg     numeric(10,3),
  score_qualite   int,            -- 1-10 at time of purchase
  date_achat      date not null default current_date,
  acheteur_id     uuid references users(id) on delete set null,
  notes           text,
  created_at      timestamptz not null default now()
);

create index if not exists idx_prix_historique_fournisseur_product
  on prix_historique_fournisseur(product_id, date_achat desc);

-- ── TABLE: orders (commandes) ─────────────────────────────────
create table if not exists orders (
  id              uuid primary key default gen_random_uuid(),
  reference       text unique,    -- CMD-YYYYMMDD-NNN
  client_id       uuid references clients(id) on delete set null,
  prevendeur_id   uuid references users(id) on delete set null,
  livreur_id      uuid references users(id) on delete set null,
  depot_id        uuid references depots(id) on delete set null,
  status          order_status not null default 'brouillon',
  date_commande   timestamptz not null default now(),
  date_livraison  date,
  montant_total   numeric(10,2) default 0,
  montant_paye    numeric(10,2) default 0,
  modalite_paiement text default 'cash',
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

drop trigger if exists orders_updated_at on orders;
create trigger orders_updated_at
  before update on orders
  for each row execute function set_updated_at();

-- ── TABLE: order_lines ────────────────────────────────────────
create table if not exists order_lines (
  id              uuid primary key default gen_random_uuid(),
  order_id        uuid not null references orders(id) on delete cascade,
  product_id      uuid not null references products(id) on delete restrict,
  quantite        numeric(10,3) not null,
  prix_unitaire   numeric(10,2) not null,
  remise_pct      numeric(5,2) default 0,
  montant_ligne   numeric(10,2) generated always as (quantite * prix_unitaire * (1 - remise_pct/100)) stored,
  notes           text
);

-- ── TABLE: hr_docs ────────────────────────────────────────────
-- Documents RH générés par OURAI (contrats, fiches de paie, attestations)
create table if not exists hr_docs (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references users(id) on delete cascade,
  type            hr_doc_type not null,
  titre           text not null,
  contenu_json    jsonb,          -- structured content (salaire, primes, retenues...)
  pdf_url         text,           -- stored in Supabase Storage
  periode_mois    int,            -- 1-12
  periode_annee   int,
  salaire_brut    numeric(10,2),
  cnss_salarie    numeric(10,2),
  amo             numeric(10,2),
  ir              numeric(10,2),
  net_a_payer     numeric(10,2),
  signe_par       uuid references users(id) on delete set null,
  signe_at        timestamptz,
  created_by      uuid references users(id) on delete set null,
  created_at      timestamptz not null default now()
);

create index if not exists idx_hr_docs_user_periode
  on hr_docs(user_id, periode_annee desc, periode_mois desc);

-- ── TABLE: logistics_trips ────────────────────────────────────
-- Tournées livreurs — used by Jawad for route optimization
create table if not exists logistics_trips (
  id              uuid primary key default gen_random_uuid(),
  livreur_id      uuid references users(id) on delete set null,
  depot_id        uuid references depots(id) on delete set null,
  date_tournee    date not null default current_date,
  km_parcourus    numeric(8,2),
  nb_bl_affectes  int default 0,
  nb_bl_livres    int default 0,
  taux_service    numeric(5,2) generated always as (
    case when nb_bl_affectes > 0 then (nb_bl_livres::numeric / nb_bl_affectes) * 100 else 0 end
  ) stored,
  statut          text default 'planifie',  -- planifie, en_cours, termine
  notes           text,
  created_at      timestamptz not null default now()
);

-- ── TABLE: ai_sessions ────────────────────────────────────────
-- Log des conversations agents IA (audit & apprentissage)
create table if not exists ai_sessions (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid references users(id) on delete set null,
  agent_id        text not null,  -- jawad, zizi, ourai, ashel, mustapha, simohammed...
  messages        jsonb not null default '[]',
  tokens_used     int,
  duration_ms     int,
  created_at      timestamptz not null default now()
);

-- ── ROW LEVEL SECURITY ────────────────────────────────────────
alter table users enable row level security;
alter table products enable row level security;
alter table clients enable row level security;
alter table fournisseurs enable row level security;
alter table orders enable row level security;
alter table order_lines enable row level security;
alter table hr_docs enable row level security;
alter table depots enable row level security;

-- Users: each user can read their own row + admins can read all
create policy "users_select_own" on users
  for select using (auth.uid() = id);

create policy "users_select_admin" on users
  for select using (
    exists (
      select 1 from users u
      where u.id = auth.uid()
        and u.role in ('super_admin','admin')
    )
  );

create policy "users_insert_admin" on users
  for insert with check (
    exists (
      select 1 from users u
      where u.id = auth.uid()
        and u.role in ('super_admin','admin')
    )
  );

create policy "users_update_admin" on users
  for update using (
    exists (
      select 1 from users u
      where u.id = auth.uid()
        and u.role in ('super_admin','admin')
    )
  );

-- Products: authenticated users can read; admins can write
create policy "products_select_auth" on products
  for select using (auth.uid() is not null);

create policy "products_write_admin" on products
  for all using (
    exists (
      select 1 from users u
      where u.id = auth.uid()
        and u.role in ('super_admin','admin','acheteur','ctrl_achat')
    )
  );

-- HR docs: only the user + rh_manager/admin
create policy "hr_docs_select" on hr_docs
  for select using (
    user_id = auth.uid()
    or exists (
      select 1 from users u
      where u.id = auth.uid()
        and u.role in ('super_admin','admin','rh_manager','comptable')
    )
  );

-- ── INDEXES ───────────────────────────────────────────────────
create index if not exists idx_users_role on users(role);
create index if not exists idx_users_depot on users(depot_id);
create index if not exists idx_orders_client on orders(client_id);
create index if not exists idx_orders_status on orders(status);
create index if not exists idx_orders_date on orders(date_commande desc);
create index if not exists idx_order_lines_order on order_lines(order_id);
create index if not exists idx_clients_prevendeur on clients(prevendeur_id);
create index if not exists idx_logistics_livreur on logistics_trips(livreur_id, date_tournee desc);

-- ── SEED: default depot ───────────────────────────────────────
insert into depots (id, nom, ville, actif)
values
  ('00000000-0000-0000-0000-000000000001', 'Depot Principal — Casa Centre', 'Casablanca', true),
  ('00000000-0000-0000-0000-000000000002', 'Depot Casa Sud', 'Casablanca', true),
  ('00000000-0000-0000-0000-000000000003', 'Depot Rabat', 'Rabat', true)
on conflict (id) do nothing;

-- ============================================================
-- DONE. Tables: users, products, clients, fournisseurs,
--   orders, order_lines, hr_docs, logistics_trips,
--   prix_historique_fournisseur, depots, ai_sessions
-- Triggers: updated_at (all), matricule auto-generation
-- RLS: users, products, hr_docs, orders
-- ============================================================
